language: node_js
node_js:
  - 'node'
cache: yarn
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: 'dist'
  on:
    branch: master
